package com.dyz.myBatis.model;

import java.util.Date;

public class Payment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.orderNum
	 * @mbggenerated
	 */
	private String ordernum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.num
	 * @mbggenerated
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.price
	 * @mbggenerated
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.date
	 * @mbggenerated
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.ticket
	 * @mbggenerated
	 */
	private String ticket;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.finished
	 * @mbggenerated
	 */
	private Boolean finished;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.orderNum
	 * @return  the value of payment.orderNum
	 * @mbggenerated
	 */
	public String getOrdernum() {
		return ordernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.orderNum
	 * @param ordernum  the value for payment.orderNum
	 * @mbggenerated
	 */
	public void setOrdernum(String ordernum) {
		this.ordernum = ordernum == null ? null : ordernum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.uid
	 * @return  the value of payment.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.uid
	 * @param uid  the value for payment.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.num
	 * @return  the value of payment.num
	 * @mbggenerated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.num
	 * @param num  the value for payment.num
	 * @mbggenerated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.price
	 * @return  the value of payment.price
	 * @mbggenerated
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.price
	 * @param price  the value for payment.price
	 * @mbggenerated
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.date
	 * @return  the value of payment.date
	 * @mbggenerated
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.date
	 * @param date  the value for payment.date
	 * @mbggenerated
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.ticket
	 * @return  the value of payment.ticket
	 * @mbggenerated
	 */
	public String getTicket() {
		return ticket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.ticket
	 * @param ticket  the value for payment.ticket
	 * @mbggenerated
	 */
	public void setTicket(String ticket) {
		this.ticket = ticket == null ? null : ticket.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.finished
	 * @return  the value of payment.finished
	 * @mbggenerated
	 */
	public Boolean getFinished() {
		return finished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.finished
	 * @param finished  the value for payment.finished
	 * @mbggenerated
	 */
	public void setFinished(Boolean finished) {
		this.finished = finished;
	}
}